{
    "bg": "https://dlior9lx1k7r2.cloudfront.net/postphoto/02cb8b84-1012-4032-ba10-4a543e49ab2c.gif",
    "title": "Quiz de JavaScript",
    "description": "Teste os seus conhecimentos sobre JavaScript e vá do Basico ao Avançado ;)  ",
    "questions": [

      {
        "image": "https://media1.tenor.com/images/963dbf83410067b8216bf3fbeec50874/tenor.gif?itemid=5012719",
        "title": "O que é throw nem Error no codigo JavaScript ?",
        "description": "Ops Error ...",
        "answer": 0,
        "alternatives": [
           "São erros no programa, que criamos caso alguma condição não seja atendida",
           "São erros gerados automaticamente quando declaramos algo errado no codigo"
        ]
      },
      {
        "image": "https://thumbs.gfycat.com/IncredibleGrouchyEarwig-size_restricted.gif",
        "title": "O bloco Finally no JavaScript é executado independente do resultado do try/catch?",
        "description": "Essa é boa para treinar ",
        "answer": 1,
        "alternatives": [
           "false",
           "true"
        ]
      }
    ],
    "external": [
      "https://aluraquiz-css.omariosouto.vercel.app/",
      "https://aluraquiz-marvel.omariosouto.vercel.app/"
    ],
    "theme": {
      "colors": {
        "primary": "#ffeb3b",
        "secondary": "#b2a429",
        "mainBg": "#171B35",
        "contrastText": "#FFFFFF",
        "wrong": "#FF5722",
        "success": "#4CAF50"
      },
      "borderRadius": "4px"
    }
  }